repos:
  - repo: local
    hooks:
      - id: check-added-large-files
        name: check for large files
        entry: pre_commit_hooks/check_added_large_files.py
        language: system
      - id: check-merge-conflict
        name: check for merge conflicts
        entry: pre_commit_hooks/check_merge_conflict.py
        language: system
