repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: python -m black
        language: system
        types: [python]

      - id: ruff
        name: ruff (lint+fix)
        entry: python -m ruff check --fix
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: python -m isort
        language: system
        types: [python]
