"""Helper services for the email bot package."""

from .cooldown import (
    APPEND_TO_SENT,
    COOLDOWN_DAYS,
    COOLDOWN_WINDOW_DAYS,
    SENT_MAILBOX,
    CooldownHit,
    CooldownService,
    audit_emails,
    build_cooldown_service,
    check_email,
    get_last_sent_at,
    is_under_cooldown,
    mark_sent,
    normalize_email,
    normalize_email_for_key,
    should_skip_by_cooldown,
    was_sent_recently,
    _merged_history_map,
)

__all__ = [
    "APPEND_TO_SENT",
    "COOLDOWN_DAYS",
    "COOLDOWN_WINDOW_DAYS",
    "SENT_MAILBOX",
    "CooldownHit",
    "CooldownService",
    "audit_emails",
    "build_cooldown_service",
    "check_email",
    "get_last_sent_at",
    "is_under_cooldown",
    "mark_sent",
    "normalize_email",
    "normalize_email_for_key",
    "should_skip_by_cooldown",
    "was_sent_recently",
    "_merged_history_map",
]
