name: EmailBot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff

      - name: Run static checks
        run: |
          ruff check .

      - name: Run API contract tests
        run: |
          pytest -q tests/test_api_contract.py

      - name: Verify exports
        run: |
          python tools/check_email_clean_exports.py
